updated nvm_version, node_version
tenantcloud/ansible-role-software-dev pull request #19
Opened 2020-06-11 10:42 UTC by odebretseni

2020-06-15 13:47 UTC, BrunIF requested changes

2020-06-15 13:47 UTC, BrunIF commented on vars/main.yml
> +nvm_node_version: "v10.21.0"
чи потрібно нам версія NVM? 
У nvm також потрібно вказувати мінорну версію?
Попробуй 
```nvm install 10```
а якщо потрібно встановлювати останню версію nvm, то це можна зробити так 
```curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/master/install.sh | bash```

2020-06-15 20:07 UTC, odebretseni commented on vars/main.yml
> +nvm_node_version: "v10.21.0"
це тіки для гнучкості, виправив на останню

2020-06-22 06:40 UTC, BrunIF approved these changes

2020-06-22 06:40 UTC, merged