added xcode, fixed mas_installed
tenantcloud/ansible-role-software-dev pull request #24
Opened 2020-09-09 08:21 UTC by odebretseni

2020-09-09 08:30 UTC, BrunIF approved these changes

2020-09-09 08:32 UTC, BrunIF requested changes

2020-09-09 08:32 UTC, BrunIF commented on README.md
> +  - xcode
то як буде ставитися xcode через mas  чи інакше? бо є і так і так.

2020-09-09 08:45 UTC, odebretseni commented on README.md
> +  - xcode
буде ставитися через mas, це тіки список всього софта що ставиться цією плейбукою

2020-09-10 15:06 UTC, BrunIF approved these changes

2020-09-10 15:07 UTC, vikfedkiv approved these changes

2020-09-10 15:08 UTC, merged