added nginx, pexpect, dns settings to docker
tenantcloud/ansible-role-software-dev pull request #29
Opened 2020-12-01 16:46 UTC by odebretseni

2020-12-02 08:26 UTC, BrunIF requested changes

2020-12-02 08:26 UTC, BrunIF commented on README.md
>    - imagemagick
у нових все зрозуміло, а що зі старими юзерами?
Треба видалити старий софт. 
Додай таск, щоб видалило весь непотрібний софт і тільки потім встановило все що потріьбно.

2020-12-02 08:26 UTC, BrunIF commented on README.md
>    - java@8
потрібно спитати розроників чи не будуть оновлювати версію.

2020-12-02 08:45 UTC, BrunIF commented on README.md
> +  - pexpect
для чого ставиш цей пакет?

2020-12-02 09:30 UTC, odebretseni commented on README.md
> +  - pexpect
Далі коли я буду інсталити проект в нас є скрипт - **nfs.sh**, він інтерактивно запитує "yes" та sudo пароль - того я хочу заюзати [цей](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/expect_module.html) модуль - але я ще на стадії дослідження його - він ніби працює але не зовсім. Так ось цей модуль потребує ліби **pexpect** - і я її на стадії дев софта ставлю.

2020-12-02 09:34 UTC, odebretseni commented on README.md
>    - imagemagick
таск має бути в ролі інстала софта? чи це має бути окрема роль яку ми маємо проганяти перед встановлення софта, накшталт:
```
  roles:
    - geerlingguy.mas
    - tenantcloud.delete_software_dev
    - tenantcloud.software_dev
```

2020-12-02 13:14 UTC, BrunIF commented on README.md
>    - imagemagick
в нашій ситуації простіше зробити таск у існуючі ролі і видалити непотрібний софт. Ставити його перед встановленням потрібного софта.

2020-12-02 13:22 UTC, BrunIF commented on README.md
> +  - pexpect
так позабирай всі `read` де не потрібно і не буде нічого питати. Там ж скрипт, а не бінарник. 
Щоб не було помилкового запуску, то можеш якийсь параметр додати без якого не буде виконуватися сценарій. 
Це вже оверінженірінг.

2020-12-02 13:22 UTC, BrunIF commented on README.md
>    - imagemagick
+ README.md

2020-12-02 13:29 UTC, odebretseni commented on README.md
> +  - pexpect
о - цей підхід крутий) я думав так не можно)

2020-12-04 10:42 UTC, BrunIF approved these changes

2020-12-04 10:42 UTC, merged