return local node to install
tenantcloud/ansible-role-software-dev pull request #31
Opened 2021-01-26 11:56 UTC by odebretseni

2021-01-26 13:21 UTC, BrunIF requested changes

2021-01-26 13:21 UTC, BrunIF commented on README.md
> +  - node@12
а нащо ставити ноду так. А потім будеш її перебивати через nvm?

2021-01-26 13:21 UTC, BrunIF commented on README.md
> +    pm2: 'false'
для чого нам pm2? Ми не використовуємо його у проекті.

2021-01-26 13:52 UTC, odebretseni commented on README.md
> +  - node@12
не зозумів - завжди ж ставили через nvm

2021-01-26 13:55 UTC, odebretseni commented on README.md
> +    pm2: 'false'
В нас є ще пустий ansible-laravel проект - за допомогою нього можно проінсталити наприклад emailer якій потребує цих старих сокетів - відповідно я в дев софті ставлю всякі такі нюанси. Я раніше питався за це і вирішили що всі пакети не в ролях з проектами а в ролях з софтом.

2021-01-26 14:36 UTC, BrunIF commented on README.md
> +  - node@12
ти ставиш nvm через який ставиш ноду, і окремо ставиш ноду 12-ої версії. 
Визачся. Або через nvm або без нього.

2021-01-26 14:37 UTC, BrunIF commented on README.md
> +    pm2: 'false'
тоді ок. Я вже й забув, що є архаїзми, а роль у нас крута =)

2021-01-26 14:41 UTC, odebretseni commented on README.md
> +  - node@12
нє нє я окремо ніде не ставлю - це рідмі файл де просто вказується що тут зі всім пакаваном буде 12 нода йти (принайми поки ми на ній) - це інформативно

2021-02-05 08:54 UTC, BrunIF approved these changes

2021-02-05 09:01 UTC, merged